#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allrun.pre
rm ./0/pointDisplacement
cp ./0.orig/pointDisplacement ./0/

# Cleanup old junk that may prevent things from starting
\rm -f comms/OpenFOAM.lock
\rm -f ../fem/break.foam

mkdir comms

# If OpenFOAM stops prematurely, trigger the external solver to stop
trap '[ -e comms/OpenFOAM.lock ] && echo "status=done" > comms/OpenFOAM.lock' EXIT TERM INT

# Simulated external solver.
# Using -scale since the input movement table is excessively large
#runApplication -overwrite \
#    lumpedPointMovement -scale 0.0001 -removeLock -slave ../files/response.txt &
#../fem/write_input2.py &
../fem/write_input_exp.py &

runApplication $(getApplication)

touch ./../fem/break.foam
#------------------------------------------------------------------------------
