#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

(cd steady && ./Allclean)
(cd transient && ./Allclean)

rm ./fem/break.foam
rm ./fem/old.dat
rm ./fem/b31.cvg
rm ./fem/b31.dat
rm ./fem/b31.frd
rm ./fem/b31.sta
rm ./fem/b31.rin
rm ./fem/b31.rout
rm ./fem/b31_old.sta

#------------------------------------------------------------------------------
