#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allrun.pre

# Cleanup old junk that may prevent things from starting
\rm -f comms/OpenFOAM.lock

runApplication $(getApplication)

#------------------------------------------------------------------------------
